name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'packages/cli/**'
      - '.changeset/**'
      - 'package.json'
      - 'bun.lock'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Configure Git
        run: |
              git config --global user.name 'Aman Varshney'
              git config --global user.email 'amanvarshney.work@gmail.com'

      - name: Create Release Pull Request or Publish
        uses: changesets/action@v1
        with:
          publish: bun run publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
